### ISSUE TITLE
无法输出文章

### ISSUE THREAD

**Issue by frcgty** [Meekdai/Gmeek#1]
![屏幕截图 2023-08-04 103116.png](https://pic5.58cdn.com.cn/nowater/webim/big/n_v2dc64bbdddd854a65a1534aa7798fdc51.png)

**Comment by Meekdai** [comment]
你之前是否已经生成过，然后现在又修改了config.json文件的内容？
建议通过Actions->build Gmeek->Run workflow->里面的按钮全局重新生成一次就行。

**Comment by frcgty** [comment]
没有之前生成又修改配置的情况，重新生成也试过了依然无效。检查docs目录内无post目录。

**Comment by Meekdai** [comment]
请确保每一篇文章有且仅有一个`Label`，为了防止他人提交的Issue也被抓取生成文章。

**Comment by frcgty** [comment]
是的，只设置了一个标签。

**Comment by Meekdai** [comment]
你先通过Actions->build Gmeek->Run workflow->里面的按钮手动全局重新生成一次，我看看是哪里的BUG

**Comment by frcgty** [comment]
成功输出了。
昨天我也试了手动全局输出，不知道为什么没有成功。

感谢解答！

**Comment by Meekdai** [comment]
恩恩，大部分如果出现奇奇怪怪的问题，通过上面的办法手动全局重新生成一次大概率是没有问题的。

**Comment by ibanka2020** [comment]
修改index.html没触发actions

**Comment by Meekdai** [comment]
> 修改index.html没触发actions

@ibanka2020 你在哪里看到可以修改index.html会触发actions？
