### ISSUE TITLE
能帮忙看下为什么action失败吗？

### ISSUE THREAD

**Issue by ShixiangWang** [Meekdai/Gmeek#10]
https://github.com/OncoHarmony-Network/OncoHarmony-Network.github.io/actions/runs/7055125706/job/19205236869

我这边不清楚是什么原因。

**Comment by Meekdai** [comment]
建议通过Actions->build Gmeek->Run workflow->里面的按钮全局重新生成一次

**Comment by Meekdai** [comment]
我发现你的问题了，你写了两个标题一样的issue，《使用说明》，删除那个close掉issue，再试试，这是个BUG，后续修复。

**Comment by ShixiangWang** [comment]
感谢！
