### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by weishenHong** [Meekdai/Gmeek#12]
![image](https://github.com/Meekdai/Gmeek/assets/57124685/2be455bf-431c-48bc-92f1-1191842c82eb)
是因为我某些issue只有标题没有内容吗？

**Comment by Meekdai** [comment]
对的，你需要写些内容在里面

**Comment by weishenHong** [comment]
> 对的，你需要写些内容在里面

也許後面可以優化一下？很多時候只想記錄下一個title，後面有空才去寫內容

**Comment by Meekdai** [comment]
@weishenHong 
最新版本已经添加此功能，具体见 [Gmeek更新日志](https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html)
