### ISSUE TITLE
建议更换关于 Staticfile 的 CDN 源

### ISSUE THREAD

**Issue by molikai-work** [Meekdai/Gmeek#121]
此时此刻，访问不了，
```
http://cdn.staticfile.net/Primer/21.0.7/primer.css
```

听说 staticfile.net 早就停止维护了，也是查的消息

https://www.landiannews.com/archives/101957.html
https://hostloc.com/thread-1262610-1-1.html

**Comment by molikai-work** [comment]
其实感觉就这几个文件速度也不会快多少，不如把项目中使用的资源放在存储库中，
GitHub 背后是厉害，但是保不证 CDN 源怎么样。

**Comment by molikai-work** [comment]
16:39 现在能访问 cdn.staticfile.net 了（尴尬

**Comment by amorphobia** [comment]
@Meekdai @molikai-work 

请求重开这个 issue，因为 uBlock Origin 规则 Badware risks 包含了如下一条：

```
||staticfile.net^$all
```

使用了 uBO 就会导致页面没有 css，但访客不一定知道如何修改 block 规则

**Comment by Meekdai** [comment]
好的，后面一个版本打算把这作为一个配置选项，让大家配置自己喜欢的CDN。

**Comment by Meekdai** [comment]
已经添加自定义配置`primerCSS`
更新日志：https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html
