### ISSUE TITLE
请求此 Gmeek 程序的许可证信息 license

### ISSUE THREAD

**Issue by molikai-work** [Meekdai/Gmeek#123]
希望作者能为[此仓库](https://github.com/Meekdai/Gmeek)及其对应的[模板仓库](https://github.com/Meekdai/Gmeek-template)添加许可证信息，感谢！

**Comment by Meekdai** [comment]
好的，只需要保留版权声明，使用MIT License ，文件后面添加。

**Comment by molikai-work** [comment]
非常感谢。
