### ISSUE TITLE
pc端在不同的浏览器中打开网页界面不同

### ISSUE THREAD

**Issue by mintonight** [Meekdai/Gmeek#126]
google浏览器：
![image](https://github.com/Meekdai/Gmeek/assets/115227322/f8bdabe7-0278-48ab-bed2-b9b9aabc3283)

夸克浏览器：
![image](https://github.com/Meekdai/Gmeek/assets/115227322/09d77e67-dfba-429b-88d6-1e08c07ddbff)

**Comment by mintonight** [comment]
找到问题了，是广告拦截插件的问题，但是想问一下作者为什么这个会被识别成广告
![image](https://github.com/Meekdai/Gmeek/assets/115227322/eb7dc2da-322d-49bc-8c93-685745b0f924)

**Comment by Meekdai** [comment]
这是因为Staticfile 的 CDN 源的问题，最近会更新一个版本解决这个问题的。
https://github.com/Meekdai/Gmeek/issues/121#issuecomment-2198023239

**Comment by Meekdai** [comment]
已经更新了，可以通过配置实现自定义CDN链接
