### ISSUE TITLE
为什么我的“Settings中Pages->Build and deployment->Source“这里没法选择？

### ISSUE THREAD

**Issue by linyewei** [Meekdai/Gmeek#13]
下拉选框是禁用的

**Comment by Meekdai** [comment]
> 下拉选框是禁用的

可以截图看一下吗？正常应该是可以选择的。你可以删除一下重新开始试试。

**Comment by linyewei** [comment]
> Reference

没问题了。不知道为什么在家里的电脑就可以选。但是现在打开是404
![404](https://github.com/Meekdai/Gmeek/assets/9046057/e10f0bac-f380-4f54-9674-85fc4ff097a6)

**Comment by Meekdai** [comment]
我目前已经可以访问了 https://linyewei.github.io/

**Comment by linyewei** [comment]
> https://linyewei.github.io/

好的，谢谢
