### ISSUE TITLE
请求功能：将文章标签应用于页面的元标记，或自定义元标记

### ISSUE THREAD

**Issue by molikai-work** [Meekdai/Gmeek#135]
## 可以做搜索引擎优化
就是将添加到文章的标签自动应用于构建页面中的标签。

```
<meta name="keywords" content="">
```

例如在写 issues 的时候设置了标签`Cloudflare`、`免费`、`教程`，
那么最终的文章页面的元标记中就有

```
<meta name="keywords" content="Cloudflare, 免费, 教程">
```

或许可以通过这样的修改来进行搜索引擎优化。

---

## 或者是可以自定义元标记

Gmeek 可以自定义单篇文章页面的 style 和 script，或许也可以增加个自定义元标记

```
<!-- ##{"meta":"<meta name="keywords" content="...">"}## -->
```

`meta` 标签必须位于 `head` 中才能生效，实现可以自定义元标记也可以丰富功能，

例如也能自定义单篇文章的 robots 信息。

```
<meta name="robots" content="nofollow">

...

<!-- ##{"meta":"<meta name="robots" content="nofollow">"}## -->
```

---

不好意思这个请求的实际用处可能有些单一，或者不需要。

**Comment by Meekdai** [comment]
@molikai-work 功能已经添加，可通过`head`或者`allHead`配置实现，具体见下面链接
https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html
