### ISSUE TITLE
没有成功

### ISSUE THREAD

**Issue by Lionlion120** [Meekdai/Gmeek#14]
第一次用github……操作一通还是做不来

**Comment by Meekdai** [comment]
建议删除你原来的
[Lionlion120.github.io](https://github.com/Lionlion120/Lionlion120.github.io)
然后按照下面链接里的2个步骤进行安装即可，非常简单。
https://github.com/Meekdai/Gmeek/tree/main#%E5%AE%89%E8%A3%85

**Comment by Lionlion120** [comment]
网站建立成功，但是提交issue没法更新网页内容。需要加上label并且close issue吗？在 2023年12月3日，13:18，Meekdai ***@***.***> 写道：﻿
建议删除你原来的
Lionlion120.github.io
然后按照下面链接里的2个步骤进行安装即可，非常简单。
https://github.com/Meekdai/Gmeek/tree/main#%E5%AE%89%E8%A3%85

**Comment by Meekdai** [comment]
是的，你在新打开一篇issue后，记得要添加`label`，否则不会生成，这是为了防止别人恶意提交的issue。但是不需要`close issue`。
如果出现错误以后无法正确抓取，只需要全局重新生成一次就行，建议你仔细阅读一下Gmeek的[README.md](https://github.com/Meekdai/Gmeek#readme)
