### ISSUE TITLE
TOC目录插件可能在某些情况下较难阅读

### ISSUE THREAD

**Issue by molikai-work** [Meekdai/Gmeek#144]
TOC目录插件在小屏设备的暗黑主题下，背景与文字的颜色过于相近，可能会造成一些阅读影响。
如图的小屏设备：

![1b278633cead3ad6765bf8bf616d6530](https://github.com/user-attachments/assets/f95f6a43-b284-4f02-b9ec-d150f4d0b638)

<hr />

宽屏设备显示正常：

![{72FA2BA2-744B-4254-8941-7BEB77B48F82}](https://github.com/user-attachments/assets/2b307d99-f152-471a-99d7-1a08fcf1fa7d)

**Comment by Meekdai** [comment]
谢谢，这确实是个BUG，已经修复，你可以再看看。
