### ISSUE TITLE
可以自定义公共css和js同步到所有文章而不是一个个加脚本嘛

### ISSUE THREAD

**Issue by lujunan1109** [Meekdai/Gmeek#15]
一个个加的话，每个文章都需要加一样的css和js；

**Comment by Meekdai** [comment]
后续可以添加这个功能

**Comment by Meekdai** [comment]
最新版本已经添加此功能，具体见 [Gmeek更新日志](https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html)

**Comment by lujunan1109** [comment]
如果可以单独用一个js和css文件夹单独维护全局的样式和脚本就好了，在json文件配置的话我发现js文件比较多的时候，比较麻烦，除非是线上的js文件。我的建议是能够有独立的脚本文件来维护可能好很多。

**Comment by Meekdai** [comment]
> 如果可以单独用一个js和css文件夹单独维护全局的样式和脚本就好了，在json文件配置的话我发现js文件比较多的时候，比较麻烦，除非是线上的js文件。我的建议是能够有独立的脚本文件来维护可能好很多。

完全支持的，你可以在你的仓库中新建一个文件夹，里面添加js文件和css文件。然后通过config.json配置，地址填写到你的仓库对应的文件就行了。
```
"style":"<link href="myself.css" rel="stylesheet" />",
"script":"<script async src='myself.js'></script>",
```
