### ISSUE TITLE
补充一个多个插件的安装说明

### ISSUE THREAD

**Issue by TnL1fe** [Meekdai/Gmeek#152]
**背景**：看到了开发者提的插件，觉得很好用打算多加几个，但是readme中没说明怎么同时加多个插件。同时也不知道作者是否允许提交PR，所以先提一个issue。

如果想要同时使用多个插件，可以按照以下方式：
```shell
    "allHead":"<script src='https://blog.meekdai.com/Gmeek/plugins/GmeekBSZ.js'></script> <script src='https://blog.meekdai.com/Gmeek/plugins/GmeekVercount.js'></script>",
    "script":"<script src='https://blog.meekdai.com/Gmeek/plugins/articletoc.js'></script> <script src='https://blog.meekdai.com/Gmeek/plugins/lightbox.js'></script>",
```

**Comment by Meekdai** [comment]
@TnL1fe 对啊，就是你这样使用的，在[快速上手](https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html#5.-%E5%A4%9A%E7%A7%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0)中有说明的。

**Comment by TnL1fe** [comment]
> @TnL1fe 对啊，就是你这样使用的，在[快速上手](https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html#5.-%E5%A4%9A%E7%A7%8D%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0)中有说明的。

我去找了下 还真有。哈哈哈哈抱歉抱歉，我就感觉你整体写的那么详细，这个怎么不太可能会依赖
