### ISSUE TITLE
请问如何实现评论数量的展示

### ISSUE THREAD

**Issue by TnL1fe** [Meekdai/Gmeek#155]
哈喽，我看你的demo中评论是显示数量的，但是我启动的没有数量，是我漏了什么设置么

![image](https://github.com/user-attachments/assets/01b0f754-ca4d-44ce-92d5-4e277dd37064)

我的地址
https://tnl1fe.github.io/post/this%20new%20day.html

**Comment by Meekdai** [comment]
不是评论后马上就出现的，因为是静态页面，所以只有手动全局生成之后会出现。目前actions每天晚上会自动执行一次，所以一般评论后，第二天就能展示数量了。
