### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by billowssun** [Meekdai/Gmeek#159]
我什么都没有动过，今天突然报错，以下是全部代码：
1s
Run cp -r ./* /opt/Gmeek/
{'bug': '#d73a4a', 'documentation': '#0075ca', 'duplicate': '#cfd3d7', 'enhancement': '#a2eeef', 'good first issue': '#7057ff', 'help wanted': '#008672', 'invalid': '#e4e669', 'question': '#d876e3', 'wontfix': '#ffffff'}
GitHub Pages URL:  https://billowssun.github.io
blogBase is exists and issue_number!=0, runOne
Traceback (most recent call last):
  File "Gmeek.py", line 470, in <module>
    blog.runOne(options.issue_number)
  File "Gmeek.py", line 423, in runOne
    self.createPostHtml(self.blogBase[listJsonName]["P"+number_str])
KeyError: None
====== start create static html ======
Error: Process completed with exit code [1]

**Comment by liyifanniubi** [comment]
没加标签呗

**Comment by billowssun** [comment]
的确是😂

在 2024年7月27日，12:04，liyifanniubi ***@***.***> 写道：

﻿

没加标签呗
