### ISSUE TITLE
没有成功输出文章，action 报错日志如下：

### ISSUE THREAD

**Issue by Guanys-dar** [Meekdai/Gmeek#16]
![image](https://github.com/Meekdai/Gmeek/assets/113331010/18ecb7bb-5e79-44ba-a777-fca3c715d002)

非常感谢你的项目，请问这里是出了什么问题？

**Comment by Meekdai** [comment]
请给你的issue添加一个`Label`
https://github.com/Guanys-dar/DailyShare/issues/1

**Comment by Guanys-dar** [comment]
添加label后仍然存在同样的报错日志，请问是什么原因

**Comment by Meekdai** [comment]
> 添加label后仍然存在同样的报错日志，请问是什么原因

1、仓库名称没有按照`XXX.github.io`命名，你应该命名为`Guanys-dar.github.io`比较好。
2、建议通过Actions->build Gmeek->Run workflow->里面的按钮全局重新生成一次。
