### ISSUE TITLE
TOC目录插件在文章中没有标题时仍然存在占位符

### ISSUE THREAD

**Issue by molikai-work** [Meekdai/Gmeek#160]
请问能否优化一下这里？
如果文章中没有存在例如`#`、`##`的标题，占位符仍然存在。

![image](https://github.com/user-attachments/assets/3f7c92ad-11ad-4afe-85ae-167de8bfa1f3)

---

![image](https://github.com/user-attachments/assets/333050c0-06e4-4e30-bf32-04c023f11d65)

---

仅在小屏设备上最显眼，在宽屏下自动到侧边，可能不太会影响到。

![image](https://github.com/user-attachments/assets/f2d6afbc-0b32-46fd-8903-62bebd90afe0)

**Comment by Meekdai** [comment]
@molikai-work 已经优化，目前如果文章中无这些标题，则不创建TOC。请帮忙测试一下，问题是否解决？

**Comment by molikai-work** [comment]
谢谢，问题已解决，现在在无标题的情况下没有toc相关元素。
