### ISSUE TITLE
求助怎么去掉大边框

### ISSUE THREAD

**Issue by lykayang** [Meekdai/Gmeek#176]
我自己试了多次也不行。
![微信截图_20240821163624](https://github.com/user-attachments/assets/f721d494-6c46-4a60-bc83-b93ff1db76f1)

我加了一个js,已经去掉了每个标题中间的横线。想要去掉这个大边框，不知道要怎么写。向各位大哥请教！
然后这个底色能不能改成透明？

谢谢！

地址是https://github.com/lykayang/lykayang.github.io

**Comment by lykayang** [comment]
然后我用chrome F12 ，可以看到去掉这个border就可以了。问题是在JS里怎么写都没办法去掉这个定义
![微信截图_20240822084711](https://github.com/user-attachments/assets/08c2270d-befa-458f-9400-9dcc6c8434d9)

**Comment by Meekdai** [comment]
![image](https://github.com/user-attachments/assets/ee2901ff-eafe-446a-b010-b4a26690b532)

你想要这样是吧？改变SideNav的边框和背景颜色就可以了。你可以自定义CSS啊，为什么要用JS？

**Comment by lykayang** [comment]
是的。已经改了好。谢谢！
