### ISSUE TITLE
代码块的背景色怎么调整

### ISSUE THREAD

**Issue by pepliu** [Meekdai/Gmeek#188]
首先非常感谢作者提供了如此惊艳的的项目，这两天一直在折腾这个样式，无奈实在是太菜了，我现在的代码块样式是浅色的背景，如下图
![截图 2024-10-07 12-44-21](https://github.com/user-attachments/assets/e2c74b26-07ea-4297-852b-83b94dbddc40)
我想要的效果是这样的
![截图 2024-10-07 12-44-43](https://github.com/user-attachments/assets/6fb0b8e6-9f2b-4cea-b13f-01dc4a5b5d2c)
怎么才可以实现呢，求各位大佬出手帮帮忙呀，如果能实现代码行号就更好了。
![截图 2024-10-07 12-50-39](https://github.com/user-attachments/assets/da6999ba-95b4-4a67-a4ca-c626c27675c7)

**Comment by Meekdai** [comment]
这个要添加自定义CSS，如果是行号要自己写一个插件实现。

**Comment by pengs361** [comment]
> 这个要添加自定义CSS，如果是行号要自己写一个插件实现。

感谢

**Comment by pepliu** [comment]
非常感谢
