### ISSUE TITLE
直接往doc文件放入html文件可不可以生成并更新页面？

### ISSUE THREAD

**Issue by RouJiANG-14** [Meekdai/Gmeek#19]
查看了往期的issues,说是markdown转html然后再生成的

我有个疑问，那我直接往doc文件夹里塞入html文件可不可以生成更新？

**Comment by Meekdai** [comment]
在手动执行全局生成操作的时候会删除docs文件夹，所以不是一个长久的解决方案。
想问一下你是有什么需求吗？
如果只是想添加一个自己的页面，那你完全可以自己新建一个自己的仓库，把html文件放进去，然后用github默认的页面部署就可以。然后访问`xxx.github.io/yyy`。其中`xxx` 是你的github用户名，`yyy`是新创建的仓库名。
