### ISSUE TITLE
构建gmeek actionflow失败

### ISSUE THREAD

**Issue by cnhbxy5z** [Meekdai/Gmeek#191]
求，以前是正常的，改了几次都不成功，手动也不行
![Screenshot_2024-10-12-22-06-41-084_com android chrome](https://github.com/user-attachments/assets/16aeca28-f99f-4672-8c00-62eefc3aca1b)

**Comment by hst1189** [comment]
@cnhbxy5z  
检查一下 最后一行       貌似多了一个逗号
![image](https://github.com/user-attachments/assets/e56ddedd-cb64-44e0-9da0-260abbd898cf)

**Comment by cnhbxy5z** [comment]
删去后依旧不成功

**Comment by hst1189** [comment]
@cnhbxy5z 
上面的地方 貌似漏了一个逗号 
![image](https://github.com/user-attachments/assets/18804fb8-0f20-4720-963e-fd9e17dbb2cb)

**Comment by cnhbxy5z** [comment]
![Screenshot_2024-10-13-22-39-48-605_com android chrome](https://github.com/user-attachments/assets/fa5bbe20-49f5-4337-a2b0-4fdf620cf3b1)
原因未知

**Comment by Meekdai** [comment]
@cnhbxy5z 你的json格式错误。复制你的json数据到下面这个校验的网站，就知道哪里出问题了。

https://m.bejson.com/json/format/

**Comment by cnhbxy5z** [comment]
> @cnhbxy5z 你的json格式错误。复制你的json数据到下面这个校验的网站，就知道哪里出问题了。
> 
> https://m.bejson.com/json/format/

![Screenshot_2024-10-20-23-16-50-913_com android chrome](https://github.com/user-attachments/assets/e95a5d2e-eee3-448b-b5ab-753d0af846e6)
![Screenshot_2024-10-20-23-17-14-506_com android chrome](https://github.com/user-attachments/assets/9b154d57-e08f-4115-aa3e-f8bae2fed107)
json好像没问题了，但构建还是有问题

**Comment by Meekdai** [comment]
@cnhbxy5z 你先弄明白json配置里面的参数都什么作用再配置好么？用不到的参数不要配置。你现在的错误就是因为`homeUrl`这个参数你没有用到，配置为空导致的。
