### ISSUE TITLE
评论区无法展开

### ISSUE THREAD

**Issue by Sylar-W** [Meekdai/Gmeek#199]
![image](https://github.com/user-attachments/assets/9f0fc1c6-e69a-450f-a4bc-b0a73f96f195)
默认使用了黑色主题，github 也安装了utteranc app

另外还想请教一下，这个项目是在issue里写博客，而且是public的，是否会有其他人也可以在上面恶意提issue？

感谢作者，期待答复

**Comment by Sylar-W** [comment]
第一个问题是我疏忽了，仔细看了一下utteranc 的默认黑色是只支持github-dark，修改后可以了，第二个问题想请教一下

**Comment by Meekdai** [comment]
第二个问题，恶意提交不会被抓取，因为必须要添加一个label才会被抓取的。

**Comment by Sylar-W** [comment]
是的 我的意思就是假设有人打广告，趁机提了一堆带label的issue咋办呢 😅

**Comment by Meekdai** [comment]
@Sylar-W 你怕是不知道只有仓库所有者才能添加label吧？

**Comment by Sylar-W** [comment]
不好意思 谢谢解答
另外感谢作者开源❤
