### ISSUE TITLE
没看懂 readme，操作失败

### ISSUE THREAD

**Issue by d100972** [Meekdai/Gmeek#20]
按照步骤 1,2,3 完成后，测试未成功，仓库要有什么代码嘛？现在 action 的直接是我的 readme  
第二步是这样的 
![Uploading iShot_2023-12-14_16.31.38.png…]()

**Comment by Meekdai** [comment]
第一步就错了

1、删掉你现在创建的
2、点击[创建仓库](https://github.com/new?template_name=Gmeek-template&template_owner=Meekdai)，建议仓库名称为XXX.github.io，其中XXX为你的github用户名。

点击创建仓库，是让你直接点击啊，创建仓库几个字不是可以点进去的吗？
