### ISSUE TITLE
无法显示.ico格式的favicon图标

### ISSUE THREAD

**Issue by dishao123** [Meekdai/Gmeek#200]

**Comment by Meekdai** [comment]
我看你的页面已经显示了。
![image](https://github.com/user-attachments/assets/6813ed32-3a0e-45a4-a620-ee170111f0cb)

**Comment by dishao123** [comment]
> 我看你的页面已经显示了。 ![image](https://private-user-images.githubusercontent.com/11755104/386039996-6813ed32-3a0e-45a4-a620-ee170111f0cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NjQwODcsIm5iZiI6MTczMTU2Mzc4NywicGF0aCI6Ii8xMTc1NTEwNC8zODYwMzk5OTYtNjgxM2VkMzItM2EwZS00NWE0LWE2MjAtZWUxNzAxMTFmMGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA1NTYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNGYwM2U3YmEwNmEwODg4MzJhYmZmNzQwYTNjMWMyMTE2ZjE5YWM2MzI2YzdkNzQ2OTg2ZjYyN2EwNzU0YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MJUhOKWqZnVJ2kan6n_EN4uDhtcTkgBrk5iZ3F2l4gU)

为什么通过 Google 的 API 获取不到 Favicon 图片。

[https://www.google.com/s2/favicons?domain=https://blog.dishao.de/&sz=32](https://www.google.com/s2/favicons?domain=https://blog.dishao.de/&sz=32)

![faviconV2-16×16--11-14-2024_02_00_PM](https://github.com/user-attachments/assets/935f95df-cd76-449c-b0c4-58ec20564af7)

**Comment by Meekdai** [comment]
那就不是Gmeek的问题了，页面是能正常显示的，你要看的是为什么Google 的 API 获取不到 Favicon

**Comment by dishao123** [comment]
> 那就不是Gmeek的问题了，页面是能正常显示的，你要看的是为什么Google 的 API 获取不到 Favicon

ok
