### ISSUE TITLE
文章内无法通过锚点跳转h1-h6标题

### ISSUE THREAD

**Issue by dishao123** [Meekdai/Gmeek#216]
我在[这篇文章](https://blog.xwdev.com/post/13.html)中，使用`[跳转标题](#标题)`的方式，进行跳转发现，点击后没反应，不知道是我的姿势不对，还是什么原因

![RackNerd-服务器-IPv6-配置教程-12-25-2024_11_17_PM](https://github.com/user-attachments/assets/837bec6d-edb5-420a-94bc-f3ec50558675)

---

![RackNerd-服务器-IPv6-配置教程-·-Issue-13-·-dishao123-dishao123-github-io-12-25-2024_11_19_PM](https://github.com/user-attachments/assets/6bb5f756-f87c-4028-97c3-61aa018ab08f)

---

我需要跳转到这里
![RackNerd-服务器-IPv6-配置教程-·-Issue-13-·-dishao123-dishao123-github-io-12-25-2024_11_22_PM](https://github.com/user-attachments/assets/8315f7ed-414a-458d-a19c-4691835f3996)

**Comment by GJKen** [comment]
你这姿势不对, [文字内容](#跳转地址,如果含有空格需要转成`-`符号)

**Comment by GJKen** [comment]
我看了下是因为你的博客没有生成标题的id导致无法跳转锚点
具体为何没有id我就不清楚了

![image](https://github.com/user-attachments/assets/20536d84-884a-4598-a257-6998e2d6f212)

**Comment by dishao123** [comment]
> 我看了下是因为你的博客没有生成标题的id导致无法跳转锚点 具体为何没有id, 因为有id定位的博客我看了下基本上都是使用了文章目录toc这个脚本生成的
> 
> ![image](https://private-user-images.githubusercontent.com/69197105/398838563-20536d84-884a-4598-a257-6998e2d6f212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODQzMjcsIm5iZiI6MTczNTI4NDAyNywicGF0aCI6Ii82OTE5NzEwNS8zOTg4Mzg1NjMtMjA1MzZkODQtODg0YS00NTk4LWEyNTctNjk5OGUyZDZmMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA3MjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWUyMjg5ODljNTMyY2EwYzYwMjUwZWIwMzBhYWRkYmRjZmM0YTkxZjBmNGIzZGZkNGIwNzMyYmZiM2I3ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.21kOfK4JnX-JD0loT-eqiMrW0sKybCdL5u42iTdE1Yw)

我没有使用toc插件，因为我不需要生成目录的功能

**Comment by dishao123** [comment]
> 我看了下是因为你的博客没有生成标题的id导致无法跳转锚点 具体为何没有id, 因为有id定位的博客我看了下基本上都是使用了文章目录toc这个脚本生成的
> 
> ![image](https://private-user-images.githubusercontent.com/69197105/398838563-20536d84-884a-4598-a257-6998e2d6f212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODQzMjcsIm5iZiI6MTczNTI4NDAyNywicGF0aCI6Ii82OTE5NzEwNS8zOTg4Mzg1NjMtMjA1MzZkODQtODg0YS00NTk4LWEyNTctNjk5OGUyZDZmMjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA3MjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWUyMjg5ODljNTMyY2EwYzYwMjUwZWIwMzBhYWRkYmRjZmM0YTkxZjBmNGIzZGZkNGIwNzMyYmZiM2I3ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.21kOfK4JnX-JD0loT-eqiMrW0sKybCdL5u42iTdE1Yw)

请问有什么办法实现跳转吗？

**Comment by dishao123** [comment]
> 你问gpt帮你写一个就行了, 遍历文章的h1-h6标题

解决了，我把作者的toc插件改了一下，删除了toc和top功能，仅保留了生成id功能，舒服了
