### ISSUE TITLE
请问只支持单个label是出于什么考虑？

### ISSUE THREAD

**Issue by supery-chen** [Meekdai/Gmeek#22]
如题

**Comment by Meekdai** [comment]
因为当初做的时候，我的需求就是单个`label`即可，后续可以考虑添加多`label`的支持。

**Comment by Meekdai** [comment]
@supery-chen 
新版本v2.15 目前已经支持多label，具体可看[更新日志](https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html)，以及[快速上手](https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html)

**Comment by supery-chen** [comment]
赞一个
