### ISSUE TITLE
singlePage建立独立页面

### ISSUE THREAD

**Issue by zhuzhengwen** [Meekdai/Gmeek#220]
Hi，请问 singlePage 如何建立独立页面

**Comment by zhuzhengwen** [comment]
我是用about作为标签后访问提示404

**Comment by Meekdai** [comment]
看下面这个链接
https://blog.meekdai.com/post/%E3%80%90Gmeek-jin-jie-%E3%80%91-you-shang-jiao-yuan-an-niu-pei-zhi.html
