### ISSUE TITLE
按照安装顺序依然安装失败，1.创建库2.更改仓库设置3.添加issue并设置标签

### ISSUE THREAD

**Issue by yxdm1** [Meekdai/Gmeek#27]
用户名yxdm1，按照顺序创建完成后为何访问yxdm1.github.io还是404呢

**Comment by Meekdai** [comment]
@yxdm1 
你弄错了，仓库名称是应该是`yxdm1.github.io`，你现在是`yxdm1`

如果是`yxdm1`，你需要访问下面这个链接。
https://yxdm1.github.io/yxdm1

**Comment by yxdm1** [comment]
@Meekdai 

> @yxdm1 你弄错了，仓库名称是应该是`yxdm1.github.io`，你现在是`yxdm1`
> 
> 如果是`yxdm1`，你需要访问下面这个链接。 https://yxdm1.github.io/yxdm1



> @yxdm1 你弄错了，仓库名称是应该是`yxdm1.github.io`，你现在是`yxdm1`
> 
> 如果是`yxdm1`，你需要访问下面这个链接。 https://yxdm1.github.io/yxdm1

感谢，已解决
