### ISSUE TITLE
singlePage为什么在首页显示不出来

### ISSUE THREAD

**Issue by shangzhouwan** [Meekdai/Gmeek#29]
你好，singlePage 在config /base config 都加上了，也build 成功了，直接通过url 可以访问，为什么在首页显示不出来呀？需要加什么配置吗

**Comment by Meekdai** [comment]
你还需要的是指定一个`issue`为`about`，即添加about标签，link同理。
https://github.com/Meekdai/meekdai.github.io/issues/1

**Comment by shangzhouwan** [comment]
> 的是指定一个`issue`为`about`

好的，谢谢
