### ISSUE TITLE
建议 Gmeek.py 把 backup_dir 和 root_dir 都写成参数形式

### ISSUE THREAD

**Issue by shenweiyan** [Meekdai/Gmeek#3]
https://github.com/Meekdai/Gmeek/blob/fa459be2f4f30d80ae0ccb0f6f957fbd6e6d5ded/Gmeek.py#L34 
源程序中把几个目录都写死了，用户想要更改只能改代码了~

**Comment by Meekdai** [comment]
`self.root_dir='docs/'` 这个路径不会体现在博客的任何地方，写成参数没有必要。
`self.post_folder='post/'` 这个会体现在URL路径中，例如 https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html 中的`post`就是由`self.post_folder`定义。
`self.backup_dir='backup/'` 这个路径就是备份到GitHub仓库文件夹的名称。

以上，可以把`self.post_folder`和`self.backup_dir` 通过参数的形式修改，`self.root_dir`修改没有意义。

**Comment by shenweiyan** [comment]
我是把 Gmeek.py 当作导出工具来用了 ....

**Comment by Meekdai** [comment]
如果是当导出工具的话很简单，你可以在`.github/workflows/Gmeek.yml`文件中，添加指令，修改一下原有的文件夹名称就可以了，Gmeek.py是不用修改的。
