### ISSUE TITLE
大佬，能否大致讲讲原理

### ISSUE THREAD

**Issue by tongchangD** [Meekdai/Gmeek#33]
大佬，能否大致讲讲这种原理

我不太会html js 相关的东西，我完全照着您的模板在本地建仓后，很多东西都沿用了您原始仓的东西，而我想根据自己的来调整。

so，直接重建新仓，然后将原始仓中的一些文件拷贝进去，但是一直都不成功，没有出现issue 中的内容

不知是时间没有等待太久，还是有其他不知名原因，望请解答。

祝好，
tongchangD

**Comment by Meekdai** [comment]
具体可以参考下面的链接：
https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html

另外我看你的仓库，[tongchangD.github.io1](https://github.com/tongchangD/tongchangD.github.io1)，为什么后面会多一个1？而名字正确的仓库[tongchangD.github.io](https://github.com/tongchangD/tongchangD.github.io)，却不是以https://github.com/Meekdai/Gmeek-template 创建的。

请严格按照文章《Gmeek快速上手》来创建，谢谢。
