### ISSUE TITLE
生成失败

### ISSUE THREAD

**Issue by QAbot-zh** [Meekdai/Gmeek#35]
一开始没注意到说要手动全局构建一次，补了构建后还是没能成功，该怎么修复？

![image](https://github.com/Meekdai/Gmeek/assets/40236765/d5d47132-fb03-43c8-88f5-8a8508d34405)

![image](https://github.com/Meekdai/Gmeek/assets/40236765/df99dfa9-fff2-438b-be8c-14a001045fce)

**Comment by Meekdai** [comment]
@QAbot-zh 我看到你的issues没有添加一个标签

**Comment by QAbot-zh** [comment]
> @QAbot-zh 我看到你的issues没有添加一个标签

原来如此，还没怎么用过issue的label功能，了解了

**Comment by Meekdai** [comment]
@QAbot-zh 恩恩，加标签就是为了防止别人恶意提交issues，污染自己的博客内容。因为只有自己可以添加label。
