### ISSUE TITLE
新增issue 文章不推送到blog

### ISSUE THREAD

**Issue by hulu5** [Meekdai/Gmeek#37]
现象：新增issue 文章不推送到blog
ACTION 异常：
      Run cp -r ./* /opt/Gmeek/
      {'bug': '#d73a4a', 'documentation': '#0075ca', 'duplicate': '#cfd3d7', 'enhancement': '#a2eeef', 'good first issue': '#7057ff', 'help wanted': '#008672', 'invalid': '#e4e669', 'question': '#d876e3', 'wontfix': '#ffffff'}
      Traceback (most recent call last):
      blogBase is exists and issue_number!=0, runOne
      ====== start create static html ======
        File "Gmeek.py", line 352, in <module>
          blog.runOne(options.issue_number)
        File "Gmeek.py", line 3[22](https://github.com/hulu5/hulu5.github.io/actions/runs/8182524476/job/22373991553#step:8:23), in runOne
          self.createPostHtml(self.blogBase[listJsonName]["P"+number_str])
      KeyError: None
      Error: Process completed with exit code 1.
      
 帮忙看下咯

**Comment by Meekdai** [comment]
请先手动全局生成一次，有问题可以先看下面的文章。
https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html

**Comment by hulu5** [comment]
感谢。全局构建一下就可以了。

现在有个新问题。blog只有标题，点进去404

重现页面 https://hulu5.github.io/post/2024030703.html

**Comment by Meekdai** [comment]
你配置的第二步没有设置正确。我看你的actions里面还有 pages build and deployment 在运行。按照快速上手的步骤，一个都不要落下啊。

**Comment by hulu5** [comment]
搞定。 👍
