### ISSUE TITLE
consig.json中的script会在post的最后出现两次

### ISSUE THREAD

**Issue by jinsanity07git** [Meekdai/Gmeek#46]
问题如图所示：
![Screenshot 2024-03-25 at 10 00 26 PM](https://github.com/Meekdai/Gmeek/assets/31701385/9502c065-85f3-45f6-8415-210b9407f2bf)

原因推测：
        postBase["script"]=postBase["script"]+issue["script"]
 python代码中script被重复叠加？

**Comment by Meekdai** [comment]
@jinsanity07git 目前已经在修复中。

**Comment by Meekdai** [comment]
@jinsanity07git 目前BUG已经解决，建议手动全局生成一次就可以了。

**Comment by jinsanity07git** [comment]
高效！感谢 ❤️
