### ISSUE TITLE
试用了感觉不错，之后会考虑支持侧边栏TOC吗？

### ISSUE THREAD

**Issue by hxhac** [Meekdai/Gmeek#47]

**Comment by Meekdai** [comment]
后续可以考虑添加这个功能的。

**Comment by hxhac** [comment]
@Meekdai 感谢您的repo以及回复

**Comment by Meekdai** [comment]
@hxhac 插件功能已经支持TOC目录
https://blog.meekdai.com/post/%E3%80%90Gmeek-jin-jie-%E3%80%91-cha-jian-gong-neng-de-shi-yong.html
