### ISSUE TITLE
请问支持其他评论系统吗？

### ISSUE THREAD

**Issue by dishao123** [Meekdai/Gmeek#48]
例如自建的[waline](https://github.com/walinejs/waline)

**Comment by Meekdai** [comment]
@dishao123 由于Gmeek的特点就是All in Github ，所以目前是不支持其他评论系统的。

**Comment by dishao123** [comment]
> @dishao123 由于Gmeek的特点就是All in Github ，所以目前是不支持其他评论系统的。

好吧

**Comment by dishao123** [comment]
@Meekdai 希望考虑支持一下 [giscus](https://github.com/giscus/giscus) 评论系统，符合 Gmeek 的理念并且比 [utterances](https://github.com/utterance/utterances) 好用

**Comment by Meekdai** [comment]
@dishao123 请问[giscus](https://github.com/giscus/giscus)好用在哪里？这个我之前也看过，因为他是把评论托管在Discussions上的，没有[utterances](https://github.com/utterance/utterances)直观啊？

因为现在文章是issues，评论也就是文章issues下面的评论，不用再重新开Discussions。

**Comment by dishao123** [comment]
@Meekdai 抱歉，我没有注意到他们两个的托管方式不一样
