### ISSUE TITLE
Issue 更换 Label 后无法同步到博客中

### ISSUE THREAD

**Issue by aixcyi** [Meekdai/Gmeek#5]
更换 Label 后我试过重新运行 Action，也尝试发了新的帖子，但被更改的 Label 都没有同步过去。

**Comment by Meekdai** [comment]
恩，这个是因为修改Label 不会触发Action，你把修改Label 的文章再重新编辑，比如在文中添加一个空格保存，就会触发Action。

**Comment by aixcyi** [comment]
噢噢，也就是新加了帖子是不会编译之前的内容的对吧？

**Comment by Meekdai** [comment]
是的这个BUG，只需要在`.github/workflows/Gmeek.yml`中添加，对应的触发条件即可，我今天晚上再汇总一下，修复后再更新一个版本号。
