### ISSUE TITLE
大佬，能否支持多个label

### ISSUE THREAD

**Issue by evilvlso** [Meekdai/Gmeek#56]
是否有支持多label计划

**Comment by Meekdai** [comment]
@evilvlso 有这个计划

https://github.com/Meekdai/Gmeek/issues/22

**Comment by Meekdai** [comment]
新版本v2.15 目前已经支持多标签功能，具体可看[更新日志](https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html)
