### ISSUE TITLE
英文括号中的内容被解析成了公式

### ISSUE THREAD

**Issue by lartpang** [Meekdai/Gmeek#59]
非常棒的工具，感谢您的开发 @Meekdai 

目前遇到一个小问题。

页面上的：

![image](https://github.com/Meekdai/Gmeek/assets/26847524/44c4d32e-a446-4eb9-bdc2-61cb74369db2)

https://lartpang.github.io/me/post/%28Arixv%202403%29%20Parameter-Efficient%20Fine-Tuning%20for%20Large%20Models%20A%20Comprehensive%20Survey.html

issue里的：

![image](https://github.com/Meekdai/Gmeek/assets/26847524/2c9bdd22-14de-4665-b68a-62e668094f23)

https://github.com/lartpang/me/issues/5

**Comment by Meekdai** [comment]
@lartpang 刚刚更新的版本添加了行内公式 https://github.com/Meekdai/Gmeek/issues/51 ，这个BUG后面会修复。

**Comment by Meekdai** [comment]
@lartpang 行内公式已经删除英文括号

https://blog.meekdai.com/post/Gmeek-geng-xin-ri-zhi.html
