### ISSUE TITLE
博客能否筛选标签呢

### ISSUE THREAD

**Issue by zqisme** [Meekdai/Gmeek#6]
目前看只能显示标签，但是无法筛选特定标签的文章
![屏幕截图(37)](https://github.com/Meekdai/Gmeek/assets/61244668/498d59c6-e604-4849-b434-c912bc647041)

**Comment by Meekdai** [comment]
后续可以考虑添加这个功能

**Comment by zqisme** [comment]
> 后续可以考虑添加这个功能

还有一个问题是不支持Markdown 任务列表语法
![](https://github.com/zqisme/picx-images-hosting/raw/master/20230927/2023-09-27-20.08.37-github.com-2b6c6c7f4dca.5j4sbxotjms0.webp)

**Comment by zqisme** [comment]
> 后续可以考虑添加这个功能

 还有个问题是不支持Markdown 任务列表语法
![](https://github.com/zqisme/picx-images-hosting/raw/master/20230927/2023-09-27-20.08.37-github.com-2b6c6c7f4dca.5j4sbxotjms0.webp)

**Comment by Meekdai** [comment]
我之前也发现了这个问题，目前没有找到问题出在哪里。因为markdown格式转html格式是直接调用GitHub的API。有可能还是primer的css不支持导致。

**Comment by shyn** [comment]
@zqisme 支持了GitHub的任务列表语法，已经提交了pr @Meekdai

**Comment by Meekdai** [comment]
@zqisme 筛选标签功能已经支持，更新到最新的`last`版本即可。
@shyn 感谢你的pr，目前也已经添加到最新版本中。

**Comment by zqisme** [comment]
> @zqisme 筛选标签功能已经支持，更新到最新的`last`版本即可。 @shyn 感谢你的pr，目前也已经添加到最新版本中。

@Meekdai 感谢！另外我想请问下只要修改GMEEK_VERSION的版本号就可以是吗

**Comment by shyn** [comment]
@zqisme 写篇新文章🐶 或者去你仓库的actions里手动运行一下就好了

<img width="917" alt="截屏2023-11-27 08 40 30" src="https://github.com/Meekdai/Gmeek/assets/899449/4206ae74-1454-4f5b-9d1c-c599674c97a8">

上面的 Run workflow 按钮。
