### ISSUE TITLE
在 `style` 中所定义的 `body` 的字体，对正文无效

### ISSUE THREAD

**Issue by CarameowCookie** [Meekdai/Gmeek#65]
我定义了 `body` 的字体为 `MiSans`，效果如下图所示：

![image](https://github.com/Meekdai/Gmeek/assets/74455347/e45384d8-670a-47fc-b1bf-d4bcf6c1b36c)

发现所设置的字体，在使用 Markdown 生成的正文部分无效（可以通过数字 `3` 的样式看出）。

附上我的 `style` 字段的内容：

```HTML
"style":"<link rel='stylesheet' crossorigin='anonymous' href='https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Medium.min.css' /> <link rel='stylesheet' crossorigin='anonymous' href='https://cdn.jsdelivr.net/npm/misans@4.0.0/lib/Normal/MiSans-Bold.min.css' /> <style>body {font-family: MiSans, sans-serif;}</style>"
```

**Comment by Meekdai** [comment]
正文你需要定义·.markdown-body·的样式
```
<style>.markdown-body{font-family: MiSans, sans-serif;}</style>
```

**Comment by CarameowCookie** [comment]
> 正文你需要定义·.markdown-body·的样式
> 
> ```
> <style>.markdown-body{font-family: MiSans, sans-serif;}</style>
> ```

@Meekdai 好的谢谢，我把 `body` 改成了 `*`，现在好了。
