### ISSUE TITLE
建议模板的备案号增加链接到工信部网址

### ISSUE THREAD

**Issue by redzl** [Meekdai/Gmeek#7]
现在的备案要求越来越严了，不仅要标注备案号，而且必须要求备案号链接到工信部网址，所以希望模板里这块能调整一下

**Comment by Meekdai** [comment]
可以，后续更新可以添加这个功能

**Comment by Meekdai** [comment]
v2.5版本已经更新，该功能已经添加

**Comment by redzl** [comment]
> v2.5版本已经更新，该功能已经添加

你好，重新生成后发现备案号链接没有增加，是还需要什么其他额外操作吗？

**Comment by Meekdai** [comment]
> > v2.5版本已经更新，该功能已经添加
> 
> 你好，重新生成后发现备案号链接没有增加，是还需要什么其他额外操作吗？

https://github.com/redzl/redzl.github.io/blob/0bd853f60c74923970e07f45ad3c10569e93ca6d/config.json#L18

你没有修改到2.5啊
