### ISSUE TITLE
【功能建议】是否可以支持点击图片后直接放大显示

### ISSUE THREAD

**Issue by lartpang** [Meekdai/Gmeek#71]
当前是在独立页面展示，这样还得跳转回来，似乎有些麻烦。

**Comment by Meekdai** [comment]
这个功能完全可以通过自定义配置来实现的，比如加载一些现成的js开源库，有很多我随意列举2个，[lightbox2](https://lokeshdhakar.com/projects/lightbox2/) 和 [medium-zoom](https://francoischalifour.com/medium-image-zoom/)。
