### ISSUE TITLE
【功能建议】优化图片显示的位置

### ISSUE THREAD

**Issue by lartpang** [Meekdai/Gmeek#72]
当前是直接左对齐。或许可以再issue里直接使用html代码调整大小和对齐位置？（这个我没有尝试过）

如果不考虑手工调整，默认居中显示图像是不是会好一点？:》

**Comment by Meekdai** [comment]
这个只需要在自定义配置里面添加一些CSS代码就可以的。

当然如果你自定义配置了类似这种库[lightbox2](https://lokeshdhakar.com/projects/lightbox2/) 和 [medium-zoom](https://francoischalifour.com/medium-image-zoom/) 那就是顺带解决的事情了。

**Comment by lartpang** [comment]
通过在config.json中添加`style`配置，修改图像位置居中：

https://github.com/lartpang/blog/blob/ffe56ff204dd6a714bfe0a93f1064bf48abbb4cd/config.json#L7
