### ISSUE TITLE
showPostSource参数没作用。

### ISSUE THREAD

**Issue by ttxs8** [Meekdai/Gmeek#77]
showPostSource 设置成1，依然没有issues的链接。好奇怪...
![image](https://github.com/Meekdai/Gmeek/assets/58286237/fc26097d-3e9f-4453-b65b-b8c6062d9413)

**Comment by Meekdai** [comment]
@ttxs8 全局生成一次试一试

**Comment by Astro-Lee** [comment]
我也遇到同样的问题 https://astro-lee.github.io/

**Comment by Meekdai** [comment]
@Astro-Lee @ttxs8 发现问题了，我在快速上手中关于`showPostSource`的示例写错了，配置为`1`，不需要双引号，如下是正确的。

```
"showPostSource":1,
```

**Comment by ttxs8** [comment]
原来如此，谢谢~
