### ISSUE TITLE
singlePage配置未生效问题

### ISSUE THREAD

**Issue by capsiamese** [Meekdai/Gmeek#78]
你好, 根据issue中如何添加about的例子配置后,重新部署没有生效.
不知道是不是bug, 还是我单词哪里拼的不对.

**Comment by Meekdai** [comment]
手动全局生成一次试试

**Comment by capsiamese** [comment]
好了, 这个为啥要手动全局生成一次, 我在yaml中没看出啥区别

**Comment by Meekdai** [comment]
手动全局会全部重新抓取文章全部重新生成，配置文件也会重新加载识别。如果是发布单篇文章触发的，仅仅只是抓取这一批文章，配置文件不会重新加载识别。

这么做是为了提升文章构建效率，因为配置文件这些改好之后一般不会经常改动。
