### ISSUE TITLE
新增文章编译失败

### ISSUE THREAD

**Issue by night1008** [Meekdai/Gmeek#79]
<img width="990" alt="image" src="https://github.com/Meekdai/Gmeek/assets/3940006/1fe52d6e-889e-4b54-b723-f31e2c637c19">

**Comment by Meekdai** [comment]
请参考Gmeek快速上手页面

**Comment by night1008** [comment]
> 请参考Gmeek快速上手页面，至少需要一个标签！！！

了解，不好意思，没仔细看文档。
