### ISSUE TITLE
请问博客文章的网址可以改成issues的编号（就是1、2、3、4）吗？

### ISSUE THREAD

**Issue by fojno** [Meekdai/Gmeek#8]
拼音太长了而且看着有点傻……
或者有什么可以直接改的方法也请告诉我，麻烦了

**Comment by Meekdai** [comment]
我刚刚添加了这个功能，麻烦测试一下是否可以。
1、在你的`config.json`中添加`"urlMode":"issue"`
2、在你的`config.json`中修改`"GMEEK_VERSION":"main"`
3、全局重新生成一次

**Comment by fojno** [comment]
> 我刚刚添加了这个功能，麻烦测试一下是否可以。 1、在你的`config.json`中添加`"urlMode":"issue"` 2、在你的`config.json`中修改`"GMEEK_VERSION":"main"` 3、全局重新生成一次

重新建了github page成功实现了，直接改原本的，Actions会运行失败。
谢谢你，博客很好用，孩子很喜欢。

**Comment by fojno** [comment]
还有就是手机网页的文章页面的标题是不是有点问题？
![](https://i0.hdslb.com/bfs/new_dyn/93e5106ac1f7862bc32891c57a648abe5458422.png)

**Comment by Meekdai** [comment]
> 还有就是手机网页的文章页面的标题是不是有点问题？

没有问题，当初就是这么设计的，标题长了会自动换行，如果需要在一行内显示标题，字体就会很小。

**Comment by Meekdai** [comment]
版本已经更新到`v2.6`。
建议`config.json`中修改`"GMEEK_VERSION":"last"` 保证每次都以最新的版本生成文章。

**Comment by fojno** [comment]
> 版本已经更新到`v2.6`。 建议`config.json`中修改`"GMEEK_VERSION":"last"` 保证每次都以最新的版本生成文章。

修改了，提醒一下，你最新的配置文件忘记附上“.github/workflows/Gmeek.yml”了。

**Comment by Meekdai** [comment]
> 修改了，提醒一下，你最新的配置文件忘记附上“.github/workflows/Gmeek.yml”了。
你是说readme里面的说明吗？我现在又精简了安装流程，都不需要你自己拷贝`Gmeek.yml`和`config.json`。
