### ISSUE TITLE
已经有一个 Github Pages 的账号要怎么使用 Gmeek ？

### ISSUE THREAD

**Issue by breathiness** [Meekdai/Gmeek#82]
是只能删掉原本的仓库重新建吗？

**Comment by Meekdai** [comment]
不需要，你创建仓库名称为其他的就行，例如`blog`。则访问 https://xxx.github.io/blog 

下面是一个例子：
https://github.com/lijiaqiong/blog

**Comment by breathiness** [comment]
> 不需要，你创建仓库名称为其他的就行

主要是我在原来的仓库的issues里已经写了好几篇文章了。要搬运到新的有点麻烦啊。有没有在原仓库使用的办法？

**Comment by Meekdai** [comment]
@breathiness 可以的，你只需要把`.github/workflows`里面的内容改为[Gmeek.yml](https://github.com/Meekdai/Gmeek-template/blob/main/.github/workflows/Gmeek.yml) 即可跳过安装第一步。

**Comment by Meekdai** [comment]
还有config.json文件也要从template仓库拷贝一下。最后要手动全局生成一次即可。

**Comment by breathiness** [comment]
> 还有config.json文件也要从template仓库拷贝一下。最后要手动全局生成一次即可。

手动生成之后出现的页面有问题？这是什么情况？
![图片](https://github.com/Meekdai/Gmeek/assets/11361630/ebece5e3-4f14-4bbd-85f4-b3af5e26d3ba)
