### ISSUE TITLE
[Feature] 希望首页可以通过style修改

### ISSUE THREAD

**Issue by lisontowind** [Meekdai/Gmeek#88]
希望类似于修改文章css，可以直接在config中设置要添加到首页的css片段
比如：我在首页添加style:

`<style>#header h1 {position: absolute;left: 50%;transform: translateX(-50%);display: flex;flex-direction: column;align-items: center;margin-top: 200px;}.avatar {width: 200px;height: 200px;}.title-right {margin-left: 50%;margin-top: 500px;transform: translateX(-50%);}#header h1 a {margin-top: 30px;}</style>`

![image](https://github.com/Meekdai/Gmeek/assets/47842345/810b23b2-4b27-4d6e-9313-c1da92aad98d)

然后就拥有一个大头像居中的首页了！=v=

**Comment by Meekdai** [comment]
@lisontowind 已经添加首页script和style自定义功能，具体可以看 https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html

**Comment by Panda-Z-Coding** [comment]
大佬，请问这个咋么搞，我复制过去了，但是没有效果

**Comment by lisontowind** [comment]
> 大佬，请问这个咋么搞，我复制过去了，但是没有效果

 "indexStyle":"<style>#header{flex-direction:column;align-items:center;}.title-right{margin:unset;}h1{display:flex;flex-direction:column;align-items:center;user-select:none;}.avatar{width:30vh;height:30vh;min-width:200px;min-height:200px;margin:5vh;max-height:360px;max-width:360px;}</style>",
 在你的config里加一行这个，然后重新运行一下action就行了。

**Comment by DiYingisaDer** [comment]
@Panda-Z-Coding 解决了吗？大佬

**Comment by Meekdai** [comment]
@Panda-Z-Coding 你要实现什么？怎么修改的？预期是怎么样的？结果是怎么样的？你在哪个仓库修改的？

这个说明清楚一点，别人才好帮你定位。一句没有效果，你让我怎么解决？

**Comment by DiYingisaDer** [comment]
@Meekdai 把楼主的代码复制到Config后不呈现与楼主一样的Blog主页主题

**Comment by Meekdai** [comment]
@DiYingisaDer 我没看到你的仓库的配置文件内有楼主的代码。

**Comment by DiYingisaDer** [comment]
@Meekdai 我现在提交了，刚刚我在尝试https://blog.freeblock.cn/的配置

**Comment by Meekdai** [comment]
修改首页应该用`indexStyle`，另外你不能直接复制楼主的代码，你应该读懂CSS，然后根据你要的添加。

**Comment by DiYingisaDer** [comment]
@Meekdai 那我先去钻研一波

**Comment by DiYingisaDer** [comment]
@Meekdai 感谢，我通过自定义域后就可以了，大佬，我的blog和域名需要备案吗？

**Comment by cao-gift** [comment]
不需要，如果你需要用国内 CDN 加速需要，不过小白推荐使用亚太 CDN

**Comment by DiYingisaDer** [comment]
@cao-gift 感谢
