### ISSUE TITLE
构建失败，无法生成新的HTML

### ISSUE THREAD

**Issue by ymz2033** [Meekdai/Gmeek#97]
如图
![PixPin_2024-06-20_12-08-14](https://github.com/Meekdai/Gmeek/assets/148955759/f905e550-24d3-4388-92c6-6cef2596dee9)

**Comment by Meekdai** [comment]
请参考 https://blog.meekdai.com/post/Gmeek-kuai-su-shang-shou.html

**Comment by ymz2033** [comment]
感谢
